export { HomePage } from './HomePage/HomePage'
export { AuthPage } from './AuthPage'
export { AddEmployeePage } from './AddEmployeePage/AddEmployeePage'
export { EditEmployeePage } from './EditEmployeePage/EditEmployeePage'
export { ErrorPage } from './ErrorPage'
